clustername: rescale

# Change this to your pem file
private_key_path: "/path/to/key.pem"

# AWS instance
region: "us-west-2"
instance_type: "t2.micro"
instance_count: 1
# ami_id: "ami-d2c924b2"
ssh_user: "centos"

# Directories
config_dir: "./config/"
terraform_dir: "./terraform/"

# Files
tfvar_file_name: "override.tfvars"
tfstate_file: "terraform.tfstate"
